
'use client';

import * as React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useRouter } from 'next/navigation';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { PageHeader } from '@/components/shared/page-header';
import { useToast } from '@/hooks/use-toast';
import { TournamentSchema } from '@/types';
import { CalendarPlus } from 'lucide-react';

// Schema for creating a tournament (ID is generated by the API)
const CreateTournamentFormSchema = TournamentSchema.omit({ id: true });
type CreateTournamentFormValues = z.infer<typeof CreateTournamentFormSchema>;

export default function AddTournamentPage() {
  const router = useRouter();
  const { toast } = useToast();

  const form = useForm<CreateTournamentFormValues>({
    resolver: zodResolver(CreateTournamentFormSchema),
    defaultValues: {
      name: '',
      organizer: '',
      prizePool: '',
      dates: '',
      format: '',
      pointSystem: '',
      imageUrl: '', // Optional, so empty string is fine for initial state
      status: 'Upcoming', // Default to Upcoming
    },
  });

  async function onSubmit(data: CreateTournamentFormValues) {
    try {
      const response = await fetch('/api/tournaments', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to create tournament');
      }

      toast({
        title: 'Success!',
        description: 'Tournament added successfully.',
      });
      form.reset();
      // router.push('/tournaments'); // Optional: redirect after success
    } catch (error) {
      let errorMessage = 'An unexpected error occurred.';
      if (error instanceof Error) {
        errorMessage = error.message;
      }
      toast({
        title: 'Error',
        description: errorMessage,
        variant: 'destructive',
      });
    }
  }

  return (
    <div className="space-y-8">
      <PageHeader
        title="Add New Tournament"
        description="Fill in the details below to add a new tournament."
      />
      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          <FormField
            control={form.control}
            name="name"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Tournament Name</FormLabel>
                <FormControl>
                  <Input placeholder="Enter tournament name" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="organizer"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Organizer</FormLabel>
                <FormControl>
                  <Input placeholder="Enter organizer name" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="prizePool"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Prize Pool</FormLabel>
                <FormControl>
                  <Input placeholder="e.g., ₹1,00,00,000" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="dates"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Dates</FormLabel>
                <FormControl>
                  <Input placeholder="e.g., January 1 - January 31, 2025" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          
          <FormField
            control={form.control}
            name="status"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Status</FormLabel>
                <Select onValueChange={field.onChange} defaultValue={field.value}>
                  <FormControl>
                    <SelectTrigger>
                      <SelectValue placeholder="Select tournament status" />
                    </SelectTrigger>
                  </FormControl>
                  <SelectContent>
                    <SelectItem value="Upcoming">Upcoming</SelectItem>
                    <SelectItem value="Ongoing">Ongoing</SelectItem>
                    <SelectItem value="Completed">Completed</SelectItem>
                  </SelectContent>
                </Select>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="imageUrl"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Image URL (Optional)</FormLabel>
                <FormControl>
                  {/* Ensure field.value is not null/undefined for the input component */}
                  <Input placeholder="https://example.com/tournament-banner.png" {...field} value={field.value ?? ''} />
                </FormControl>
                <FormDescription>
                  Enter the full URL for the tournament&apos;s image or banner.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="format"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Format (Optional)</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Describe the tournament format (e.g., Squads, TPP, Online Qualifiers, LAN Finals)"
                    {...field}
                     value={field.value ?? ''}
                    rows={3}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="pointSystem"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Point System (Optional)</FormLabel>
                <FormControl>
                  <Textarea
                    placeholder="Describe the point system"
                    {...field}
                    value={field.value ?? ''}
                    rows={3}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button type="submit" disabled={form.formState.isSubmitting} className="bg-accent hover:bg-accent/90 text-accent-foreground">
            {form.formState.isSubmitting ? 'Adding Tournament...' : (
              <>
                <CalendarPlus className="mr-2 h-5 w-5" /> Add Tournament
              </>
            )}
          </Button>
        </form>
      </Form>
    </div>
  );
}

